###
POST http://localhost:9000/api/singup HTTP/1.1
Content-Type: application/json

{
    "email": "superfacilderecordar@hotmail.com",
    "pass" : "Global01.",
    "userId" : "0004",
    "displayName" : "Marta Sánchez F",
    "rol" : "01"
}
###
POST  http://localhost:9000/api/singin HTTP/1.1
Content-Type: application/json

{
    "email": "superfacilderecordar@hotmail.com",
    "pass" : "Global01."
}
###
POST  http://localhost:9000/api/singin HTTP/1.1
Content-Type: application/json

{
    "email": "superfacilderecordar@hotmail.com",
    "pass" : "Global01."
}