###
POST http://localhost:9000/api/rentalHouse HTTP/1.1
Content-Type: application/json

{
  "address": "Sorriba 29",
  "type": "Terreno",
  "bedrooms": 0,
  "bathrooms": 0,
  "isActive": false,
  "services": [
    {
      "name": "Electricidad",
      "provider": "Power Company",
      "contractDate": "2023-05-01"
    },
    {
      "name": "Agua",
      "provider": "Water Utility",
      "contractDate": "2023-05-01"
    },
    {
      "name": "Gas",
      "provider": "Gas Utility",
      "contractDate": "1-05-01"
    }
  ],
  "managedByUser": "635862e637f0e9e41a6ebe14"
}

###
GET http://localhost:9000/api/rentalHouse HTTP/1.1
Content-Type: application/json

###
GET http://localhost:9000/api/rentalHouse/64635fd1d2110d801c37359d HTTP/1.1
Content-Type: application/json

###
GET http://localhost:9000/api/rentalHouse/user/635862e637f0e9e41a6ebe14
Content-Type: application/json


###
DELETE http://localhost:9000/api/rentalHouse/627ab90d691e2b1ad85f1e9b HTTP/1.1
