###
POST http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json

{
    "email": "cr.esteban@gmail.com",
    "pass" : "Global01.",
    "displayName" : "Esteban Calderón"
}

###
GET http://localhost:9000/api/user HTTP/1.1
Content-Type: application/json

###
GET http://localhost:9000/api/user/627ab90d691e2b1ad85f1e9b HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:9000/api/user/627ab90d691e2b1ad85f1e9b HTTP/1.1
Content-Type: application/json

{
    "email": "cr.esteban@gmail.com3",
    "pass" : "unpasscualquiera3",
    "avatar" : "unavatarcualquiera3",
    "displayName" : "Esteban Calderon",
}

###
DELETE http://localhost:9000/api/user/627ab90d691e2b1ad85f1e9b HTTP/1.1
